[AB#137] Language version change to latest.
In an attempt to fix the Azure pipeline error "Program.cs(14,29): error CS8107: Feature 'async main' is not available in C# 7.0. Please use language version 7.1 or greater. [/home/vsts/work/1/s/src/ei-web-api/ei-web-api.csproj]".